backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "projets" # Used in routes, e.g., /admin/collections/blog
    label: "Projets" # Used in the UI
    folder: "content/projets" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Légende", name: "legende", widget: "string"}
      - {label: "Résumé", name: "resume", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Image de couverture", name: "thumbnail", widget: "image"}
      - {label: "Galerie d'images", name: "gallery", widget: "list", field: {label: Image, name: image, widget: image}}
      - {label: "Body", name: "body", widget: "markdown"}